name: autocore_build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      # namapaket1:
    #    description: "namapaket1"
     #   required: false
    #    default: "luci-app-"
    #    type: text
      namapaket:
        description: "namapaket"
        required: false
        default: "autocore-x86"
        type: choice
        options:
          - luci-app-tinyfilemanager
          - luci-app-netmonitor
          - luci-app-adguardhome
          - luci-theme-argon
          - luci-app-argon-config
          - autocore
          - autocore-x86
          - autocore-arm
          
        
jobs:
  build:
    name: build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - 25.12.1
          #- snapshot
        arch:
          #- aarch64_cortex-a53
          - x86_64

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build
        uses: sbwml/openwrt-gh-action-sdk@helloworld
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: ${{ github.event.inputs.namapaket }}
          NO_REFRESH_CHECK: true
         

      
         
      - name: Store packages
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          # path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
          path: bin

      - name: Zip packages
        run: |
          #zip -j ${{ matrix.arch }}-${{ matrix.sdk }}.zip bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
          #echo -e "**文件说明** 🎈:\n" >> release.txt
          #echo -e "1. 默认ssr与passwall的插件与依赖整合包\n" >> release.txt
          #echo -e "2. 使用方法：将整合包上传到openwrt设备的tmp目录，输入命令 \`opkg install *.ipk\`\n" >> release.txt
          #echo -e "3. 默认压缩包里包含ssr passwall bypass passwall2 插件\n" >> release.txt
          echo -e "testing" >> release.txt
          
      
      - name: Upload packages apk
        uses: ncipollo/release-action@main
        with:
          token: ${{ secrets.REALESES_TOKEN }}
          artifacts: "bin/targets/x86/64/packages/autocore*.apk"
          #artifacts: "${{ matrix.arch }}-${{ matrix.sdk }}.zip,bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"
          allowUpdates: true
          replacesArtifacts: true
          bodyFile: "release.txt"
          tag: ${{ matrix.arch }}_apk

      
