name: Publish

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #  inputs:
  #    release: 
  #      description: 将编译出的镜像上传到 Release
 #       required: true
  #      default: 'true'


jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
    
    steps:
    - uses: actions/checkout@v4
    - name: Uploading Release
      uses: svenstaro/upload-release-action@v2
      with:
            repo_name: zero2black/wrtbuild
            repo_token: ${{ secrets.REALESES_TOKEN }}
            file: list_packages.txt
            asset_name: ${{ github.event.repository.name }}-${{ github.sha }}
            tag: autobuildg
            overwrite: true
