name: Publish

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #  inputs:
  #    release: 
  #      description: 将编译出的镜像上传到 Release
 #       required: true
  #      default: 'true'


jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Uploading Release
      uses: ollydev/upload-release-action@master
      with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: list_packages.txt
            asset_name: "test"
            tag: autobuild
            owner: '${{ github.repo.owner }}'
            repo: 'wrtbuild'
            overwrite: true
