name: Copy luci-theme-argon Directories

on:
  workflow_dispatch:

jobs:
  copy-luci-theme-argon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v3

    - name: Clone sbwml/luci-theme-argon
      run: |
        git clone --depth 1 --branch openwrt-24.10 https://github.com/sbwml/luci-theme-argon.git temp-luci-theme-argon
        mkdir -p luci-app-argon-config
        mkdir -p luci-theme-argon
        cp -r temp-luci-theme-argon/luci-app-argon-config/* ./luci-app-argon-config/
        cp -r temp-luci-theme-argon/luci-theme-argon/* ./luci-theme-argon/
        rm -rf temp-luci-theme-argon

    - name: Commit Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add luci-app-argon-config luci-theme-argon
        git commit -m "Copy luci-app-argon-config and luci-theme-argon from sbwml (openwrt-24.10 branch)"

    - name: Push Changes to Main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main
