name: Copy autocore-arm Files

on:
  workflow_dispatch: # Trigger manually

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    # Checkout your repository
    - name: Checkout Target Repository
      uses: actions/checkout@v3

    # Remove existing autocore-arm folder if it exists
    - name: Remove Existing autocore-arm Folder
      run: |
        if [ -d "autocore-arm" ]; then
          rm -rf autocore-arm
        fi

    # Clone the source repository
    - name: Clone Source Repository
      run: |
        git clone --depth 1 --branch openwrt-24.10 https://github.com/sbwml/autocore-arm.git source_repo

    # Copy files into the autocore-arm folder
    - name: Copy Files to autocore-arm Folder
      run: |
        mkdir -p autocore-arm
        cp -r source_repo/* autocore-arm/

    # Configure Git
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # Ensure autocore-arm files are staged for commit
    - name: Stage autocore-arm Folder
      run: |
        git add autocore-arm/*

    # Commit and push changes
    - name: Commit and Push Changes
      run: |
        git commit -m "Initial copy of autocore-arm from openwrt-24.10 branch" || echo "No changes to commit"
        git push
