name: Copy Autocore

on:
  workflow_dispatch:

jobs:
  copy-luci-theme-argon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v3

    - name: Clone sbwml/luci-theme-argon
      run: |
        git clone --depth 1 --branch openwrt-24.10 https://github.com/sbwml/autocore-arm.git temp-autocorw-arm
        mkdir -p autocore-arm
        cp -r temp-autocore-arm/* ./autocore-arm/
        rm -rf temp-autocore-arm

    - name: Commit Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add luci-app-argon-config luci-theme-argon
        git commit -m "Copy sbwml (openwrt-24.10 branch)"

    - name: Push Changes to Main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main
