name: Sync autocore-arm

on:
  workflow_dispatch: # Manual trigger
  schedule: # Runs daily at midnight (optional)
    - cron: '0 0 * * *'

jobs:
  sync-autocore-arm:
    runs-on: ubuntu-latest

    steps:
    # Checkout your repository
    - name: Checkout Target Repository
      uses: actions/checkout@v3

    # Clone the source repository
    - name: Clone Source Repository
      run: |
        git clone --depth 1 --branch openwrt-24.10 https://github.com/sbwml/autocore-arm.git source_repo

    # Copy files into the autocore-arm folder
    - name: Copy Files to autocore-arm Folder
      run: |
        mkdir -p autocore-arm
        rsync -a source_repo/ autocore-arm/

    # Configure Git
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # Commit and push changes
    - name: Commit and Push Changes
      run: |
        git add autocore-arm
        git commit -m "Sync autocore-arm from openwrt-24.10 branch" || echo "No changes to commit"
        git push
