name: test autocore_build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      namapaket:
        description: "namapaket"
        required: false
        default: "autocore-x86"
        type: choice
        options:
          - luci-app-tinyfilemanager
          - luci-app-netmonitor
          - luci-app-adguardhome
          - luci-theme-argon
          - luci-app-argon-config
          - autocore
          - autocore-x86
          - autocore-arm
          
jobs:
  build:
    name: build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - 23.05.3
          - snapshot
        arch:
          - x86_64

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build
        uses: sbwml/openwrt-gh-action-sdk@helloworld
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: ${{ github.event.inputs.namapaket }}
          NO_REFRESH_CHECK: true
         
      - name: Store packages
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin

      - name: Prepare for Push
        run: |
          mkdir -p x86_v23
          cp bin/targets/x86/64/packages/autocore*.ipk x86_v23/

      - name: Push Artifacts to x86_v23 Branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B x86_v23
          cp -r x86_v23/* .
          git add autocore*.ipk
          git commit -m "Update autocore .ipk packages"
          git push origin x86_v23 --force
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 0
